export const placeTypes = {
  SELECTED_PLACE: "SELECTED_PLACE",
  ADD_FAVORITE: "ADD_FAVORITE",
  REMOVE_FAVORITE: "REMOVE_FAVORITE",
  ALL_FAVORITES: "ALL_FAVORITES",
  COUNT_FAVORITE: "COUNT_FAVORITE",
  GET_FAVORITES: "GET_FAVORITES",
};
